JDP230302-4 Created endpoints in orderController and OrderDto in doma…
piotr-grosicki/project-jdp-2303-02 pull request #4
Opened 2023-03-07 23:46 UTC by JanSikorski

…in package

2023-03-08 14:28 UTC, piotr-grosicki requested changes

2023-03-08 14:28 UTC, piotr-grosicki commented on build.gradle
> -    runtimeOnly('com.h2database:h2')
tego nie mozna usuwac, projekt sie nie zbuduje wtedy. testy na circle ci wymagaja bazy h2

2023-03-08 18:21 UTC, piotr-grosicki requested changes

2023-03-08 18:21 UTC, piotr-grosicki commented on build.gradle
> +    //runtimeOnly('com.mysql:mysql-connector-j')
nie no, oba musza zostac, jeden bedzie uzywany do uruchamiania aplikacji a drugi do testow

2023-03-10 21:36 UTC, piotr-grosicki requested changes
konflikty

2023-03-10 22:04 UTC, JanSikorski commented
ok, konflikty powinny być rozwiązane (przycisk do rozwiązania konfliktów był zablokowany, więc musiałem wykorzystać terminal)

2023-03-12 08:32 UTC, merged